### PR TITLE
Add Search

### PR DESCRIPTION
**Pull request by Rspoon3**
**Add Search Field for Mountains:**

- A new search field has been added to the mountain list screen, allowing users to quickly search for mountains by name.
- The search function is optimized to provide real-time results as the user types.

**Refactor Filter and Search Properties to Enums:**

- The existing filter and search properties have been refactored from strings or other basic types to enums.
- This change improves type safety, makes the codebase more maintainable, and enhances code readability.
- The enums ensure that only valid filter and search options are used throughout the application.

**Formatter Improvements:**
- Using SwiftUI formatting APIs
- This change improves type safety, makes the codebase more maintainable, and enhances code readability.
- This change improvements performance as the previous formatter had an a more expensive overhead

**Screenshots:**

image

### CODE REVIEW

**Comment by naturalnick** [comment]
Thanks for the PR @Rspoon3 ! The app def needs some work, I hope it wasn't too unsightly Swift programming 😅. I had some old changes that are making the merge a mess, but I'll be happy to accept these changes.

If you don't mind me asking... how did you find my app? Are you a hiker yourself?

**Comment by Rspoon3** [comment]
It's not that bad! If you want help with anymore changes just let me know.

I live it southern NH and now that the weather is cooling off, I want to do a few more of the 48 peaks. I thought about making an app to track which hikes I've already done but decided to check if the App Store already had one. Thats how I came across Summit.

**Comment by naturalnick** [comment]
@Rspoon3 Awesome. I also updated the summit coordinates (because a lot of them were incorrect) and published to the App Store so the new version is live now.

One thing I know needs to be fixed is the text inputs. For some reason there's some serious lag between when a letter is tapped and when it appears. I'm assuming it's not just me. I haven't had the time to look into it yet.

But thanks for the nudge to get me to push the updates and the updated summit coords, it was bugging me.

Cheers!

**Comment by Rspoon3** [comment]
@naturalnick I’m not seeing it, but open an issue and we can explore it further.

**Pull request merged**
